[package]
name = "rens-common"
version = "0.0.0"
edition = "2021"
rust-version = "1.72.1"

[dependencies]
derive_more = { version = "1.0.0-beta.6", features = [
    "constructor",
    "display",
    "from_str",
] }
regex = "1.10.4"
thiserror = "1.0.61"
