[package]
name = "rens-tui"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
crossterm = "0.27.0"
ratatui = "0.26.1"
rens-common = { path = "../rens-common" }
thiserror = "1.0.58"
