[build]
rustflags = [
  ## Warning ##
  "-Dclippy::pedantic",
  "-Dclippy::restriction",
  "-Dclippy::nursery",
  # "-Dclippy::cargo",
  ## Conflicts ##
  "-Aclippy::blanket_clippy_restriction_lints", # clippy::restriction               - can't enable clippy::restriction if this is enabled
  "-Aclippy::error_impl_error",                 # clippy::module_name_repetitions
  "-Aclippy::implicit_return",                  # clippy::needless-return           - remove return keyword when not needed
  "-Aclippy::mod_module_files",                  # clippy::self_named_module_files    - `./foo/mod.rs` instead of (`./foo.rs` + `./foo/*.rs`)
  "-Aclippy::pub-with-shorthand",               # clippy::pub-without-shorthand     - pub(<scope>) instead of pub(in <scope>)
  "-Aclippy::self_named_module_files",           # clippy::mod_module_files           - `./foo.rs` + `./foo/*.rs` instead of `./foo/mod.rs`
  "-Aclippy::separated_literal_suffix",          # clippy::unseparated-literal-suffix - 2.0_f32 vs 2.0f32
  ## Allowed ##
  "-Aclippy::arithmetic_side_effects",          # maths are fun
  "-Aclippy::missing_trait_methods",            # convenience
  "-Aclippy::question_mark_used",               # convenience
  "-Aclippy::print_stdout",
  "-Aclippy::pub_use",
  "-Aclippy::redundant_pub_crate",              # prefer to be explicit
  "-Aclippy::single_call_fn",                   # function only called once
  ## Maybe remove ##
  "-Aclippy::unneeded_field_pattern",            # prefer to be exhaustive
  ## Will remove ##
  "-Aclippy::missing_docs_in_private_items",
  "-Aclippy::missing_errors_doc",
]
